# Generated by Django 4.2.1 on 2024-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_booked', models.BooleanField(blank=True, default=False, null=True)),
                ('fare', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
