# Generated by Django 4.2.1 on 2024-10-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SeatBookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fare', models.FloatField(blank=True, default=0.0, null=True)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='SeatBookingApp.cities')),
                ('source_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_city', to='SeatBookingApp.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fare', models.FloatField(blank=True, default=0.0, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeatBookingApp.routes')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeatBookingApp.seat')),
            ],
        ),
    ]
