# Generated by Django 4.2.1 on 2024-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatBookingApp', '0002_routes_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_number',
            new_name='seat',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
